name: GitHub Actions Workflow
on:
workflow_dispatch:
   inputs:
     username:
       description: 'Enter your username'
       required: true
     favorite_color:
       description: 'Enter your favorite color'
       required: true
jobs:
job1:
   runs-on: ubuntu-latest
   steps:
   - name: Output Inputs
     id: input_values
     run: |
       echo "username=${{ github.event.inputs.username }}" >> $GITHUB_OUTPUT
       echo "favorite_color=${{ github.event.inputs.favorite_color }}" >> $GITHUB_OUTPUT
job2:
   needs: job1
   runs-on: ubuntu-latest
   steps:
   - name: Greeting Message
     id: greeting
     run: |
       greeting="Hello, ${{ steps.input_values.outputs.username }}! Your favorite color is ${{ steps.input_values.outputs.favorite_color }}."
       echo "GREETING=$greeting" >> $GITHUB_OUTPUT
job3:
   needs: job2
   runs-on: ubuntu-latest
   steps:
   - name: Echo Greeting
     run: |
       echo "${{ steps.greeting.outputs.GREETING }}"
   steps:
   - name: Echo Greeting
     run: |
       echo "${{ steps.greeting.outputs.GREETING }}"
